echo ""
echo "DEPRECATED: prepare-usb.sh has been replaced by build.sh"
echo ""
echo "Use instead:"
echo "  docker run --rm --privileged -v \"\$PWD/output:/work/output\" surface2-build prebuilt"
echo ""
echo "This creates output/surface2-bookworm-usb.img.xz"
echo "Flash to USB with:"
echo "  xz -dk output/surface2-bookworm-usb.img.xz"
echo "  sudo dd if=output/surface2-bookworm-usb.img of=/dev/sdX bs=4M status=progress"
exit 1
